### ISSUE TITLE
Server packet issue

### ISSUE THREAD

**Issue by Project-Xexas** [FlashHUN/FlashNPCs#4]
Trying to load Flash's NPC with my modpack on server, stuck at Loading world..., debug shows NullPointerExceptions thrown by Flash's, causing a fatal loop. Character model appears server-side, client stuck on Loading world..., Debug file shoots to 200 MB with same basic NullPointerExceptions. I have found a basic workaround by loading into a single player world, leaving, then entering Multiplayer.

Here's a fragment of the large debug file 
[debug.txt](https://github.com/FlashHUN/FlashNPCs/files/7109241/debug.txt)

Thanks for the help!

**Comment by Project-Xexas** [comment]
Perhaps an issue syncing server quests with client quests? Getting a lot of "[Render thread/INFO] [STDERR/]: [flash.npcmod.ClientProxy:syncAcceptedQuests:130]:"

**Comment by FlashHUN** [comment]
Hey there! Someone else ran into a similar issue recently, the only fix we found was to either delete their player data or recreate the world. Still unsure why this happens and why it only happens to some people.

**Comment by Project-Xexas** [comment]
Oh, I'm glad it's known! Deleting world/player data has not helped me, but creating/loading into a singe-player world then quitting and going to multiplayer fixes until client needs reloaded has worked as a workaround for me, though not others helping me test

**Comment by FlashHUN** [comment]
> Deleting world/player data has not helped me, but creating/loading into a singe-player world then quitting and going to multiplayer fixes until client needs reloaded has worked as a workaround for me, though not others helping me test

Alright, things just got like 10 times more weirder... _Why are capabilities so hard? Forge please..._

**Comment by Project-Xexas** [comment]
Still looking into it, seems to be a lot of this repeating

https://pastebin.com/TFgn7ukU
[debug.log](https://github.com/FlashHUN/FlashNPCs/files/7113697/debug.log)


Thought it may have been a conflict with Taterzens/CreRaces, but logs continue to say its a client-side problem. Still working on pruning mods to maybe find the conflict?

(Edit: .log file in case, like me, you use VSC to code and layout)

**Comment by Project-Xexas** [comment]
Hi, me again with some updated info. Reinstalled Minecraft, reinstalled forge (version 36.2.4) on both client and server, Java is up to date at Java 8 Update 301. I've trimmed all my mods down to:

-Alex's Mobs (1.12.0)
-Citadel (1.8.1)
-Ice and Fire (2.1.9)
-Flash's NPC (1.1)
Still unable to join server with just these 3 mods installed. However, this debug log seems a little more fruitful than the last?

[debugplzgod.txt](https://github.com/FlashHUN/FlashNPCs/files/7124927/debugplzgod.txt)

**Comment by stanlystark** [comment]
Same issue. Error on client when connect to server:
`[18Sep2021 14:31:59.545] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.NullPointerException: null
	at flash.npcmod.capability.quests.QuestCapabilityProvider.getCapability(QuestCapabilityProvider.java:34) ~[?:1.1]
	at flash.npcmod.ClientProxy.syncAcceptedQuests(ClientProxy.java:120) ~[?:1.1]
	at flash.npcmod.network.packets.server.SSyncQuestCapability.lambda$handle$1(SSyncQuestCapability.java:97) ~[?:1.1]
	at flash.npcmod.network.packets.server.SSyncQuestCapability$$Lambda$18842/1866194659.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at flash.npcmod.network.packets.server.SSyncQuestCapability.handle(SSyncQuestCapability.java:91) ~[?:1.1]
	at flash.npcmod.network.PacketDispatcher$$Lambda$15500/1826515685.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge-1.16.5-36.1.32-universal.jar:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$18310/1748903503.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge-1.16.5-36.1.32-universal.jar:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge-1.16.5-36.1.32-universal.jar:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge-1.16.5-36.1.32-universal.jar:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$3020/1144702392.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3022/305646302.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2644/1864127562.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$18297/600930118.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$18559/1971982494.run(Unknown Source) ~[?:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:128) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.32.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$527/2035215096.call(Unknown Source) [forge-1.16.5-36.1.32.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) [?:1.8.0_51]
	at pro.gravit.launcher.PiXELcrAFtyoUO.PIXElCraFtVUoG(Unknown Source) [Launcher.exe:?]
	at pro.gravit.launcher.PiXELcrAFtyoUO.main(Unknown Source) [Launcher.exe:?]`
	
**Conflict with alex mobs.**

**Comment by mviktor02** [comment]
Forgot to update this. Still unsure of the cause besides it being in Alex's Mobs, however I can't fix someone else's mod.

**Comment by FlashHUN** [comment]
Forgot to update this. Still unsure of the cause besides it being in Alex's Mobs. However, I cannot fix someone else's mod.

**Comment by Armandorev** [comment]
Another one here with the same issue, just now foudn by myself the cause was this mod. I am still trying to figure it out why running single world first fixes the problem temporary, but will keep thingking.  I will try also to check Alex mobs as suggested or update it. 
HOpe we can fix this, I just did a tutorial for this mod in my channel recomending it to be added to servers :D (because is a fantastic mod)

**Comment by Taknax** [comment]
I am facing a similar issue, but not with Alex Mobs installed. I think the new GeckoLib for 1.16.5 could cause it. Someone find a way to fix it?
